# server conf
server:
    port: 18080
    tomcat:
        access_log_enabled: true
        basedir: target/tomcat

# spring conf
spring:
    application.name: spring-boot-thymeleaf
    thymeleaf:
        cache: false

# logging conf
logging:
    level:
        org.springframework.web: INFO
        com.example.boot.thymeleaf: DEBUG